export * from './auth.slice';
export * from './user.slice';
export * from './admin.slice';
export * from './dish.slice';
export * from './review.slice';
export * from './order.slice';
export * from './restaurant.slice';
export * from './promotions.slice';
export * from './locality.slice';
